export const SET_WEB3 = 'SET_WEB3';
export const FIELD = 'FIELD';
export const SET_VEHICLE_ARRAY_STATE = 'SET_VEHICLE_ARRAY_STATE';

// export const SET_ACCOUNTS = 'SET_ACCOUNTS';

// export const SET_CONTRACT_INSTANCE = 'SET_CONTRACT_INSTANCE';
